name: example
description: An example project for fullscreen_scroll_view
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  fullscreen_scroll_view:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
