name: fullscreen_scroll_view
description: This is SingleChildScrollView but Expanded and Flex are available
version: 1.0.1
homepage: https://github.com/yu1ro/fullscreen_scroll_view

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
